version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: live026
    volumes:
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    ports:
      - "5432:5432"